### ISSUE TITLE
Subfolders in an MFA Zone shared with non-MFA users can be accessed and downloaded by a non-MFA user

### ISSUE THREAD

**Issue by sunetfreitag** [SUNET/nextcloud-mfazones#19] opened 2024-09-03 11:07 UTC
A subfolder in an MFA zone that has been shared with a local non-MFA user can be accessed by the non-MFA user.

**Steps to reproduce**
1. Log on with an MFA-protected user account
2. Create a folder and activate the MFA Zone
3. Create a subfolder and share it with a non-MFA user
4. Log on with the non-MFA-protected user account
5. The folder shows up and the non-MFA user can download individual files

Tested with 0.1.7 and 0.1.5 in the docker development environment.

**Comment by mickenordin** [comment] 2024-09-04 20:20
I suspect, the issue is here: https://github.com/SUNET/nextcloud-mfazones/blob/ca5c37181245dc76c0a9e7e461de973c980b7987/mfazones/lib/MFAPlugin.php#L45

**Comment by mickenordin** [comment] 2024-09-05 13:19
This should be fixed in v0.2.0. We now set mfazone recursivly on all files and folders in an mfazone.

**Closed** 2024-09-05 13:19 UTC
